collection_name: agent
url: http://localhost:6333
grpc_port: 6334
prefer_grpc: false
distance: COSINE
force_recreate: false

k: 3
per_query_top_k: 5
per_query_keep: 2
final_context_limit: 12
data_path: data
md5_hex_store: qdrant_md5.text
allow_knowledge_file_type: ["txt", "pdf"]

chunk_size: 200
chunk_overlap: 20
separators: ["\n\n", "\n", ".", "!", "?", "。", "！", "？", " ", ""]
